export const MOCK_FEED_ITEMS = [
  {
    contentId: "mock_001",
    title: "Inception",
    cover: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    genres: ["Sci-Fi", "Thriller"],
    rating: 8.8,
    synopsis: "Un ladrón que roba secretos corporativos a través del uso de la tecnología de compartir sueños, recibe la tarea de implantar una idea en la mente de un CEO.",
    type: "movie",
  },
  {
    contentId: "mock_002",
    title: "Cien años de soledad",
    cover: "https://books.google.com/books/content?id=PGR2AwAAQBAJ&printsec=frontcover&img=1",
    genres: ["Fiction", "Magical Realism"],
    rating: 4.5,
    synopsis: "La novela narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.",
    type: "book",
  },
  {
    contentId: "mock_003",
    title: "Interstellar",
    cover: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Sci-Fi", "Drama"],
    rating: 8.7,
    synopsis: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de asegurar la supervivencia de la humanidad.",
    type: "movie",
  },
  {
    contentId: "mock_004",
    title: "1984",
    cover: "https://books.google.com/books/content?id=Q1234&printsec=frontcover&img=1",
    genres: ["Fiction", "Dystopian"],
    rating: 4.5,
    synopsis: "En un futuro totalitario, Winston Smith lucha por mantener su humanidad y sus pensamientos independientes en una sociedad vigilada por el Gran Hermano.",
    type: "book",
  },
  {
    contentId: "mock_005",
    title: "The Dark Knight",
    cover: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911M1x2W0I4Jq4.jpg",
    genres: ["Action", "Drama"],
    rating: 9.0,
    synopsis: "Cuando la amenaza del Joker emerge en Gotham, Batman debe aceptar uno de los mayores desafíos de su carrera para salvar la ciudad.",
    type: "movie",
  },
  {
    contentId: "mock_006",
    title: "El principito",
    cover: "https://books.google.com/books/content?id=Y5678&printsec=frontcover&img=1",
    genres: ["Fiction", "Fantasy"],
    rating: 4.6,
    synopsis: "Un piloto perdido en el desierto conoce a un pequeño príncipe de otro planeta que le enseña lecciones sobre la vida y el amor.",
    type: "book",
  },
]
